apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: turing-firecontrol
spec:
  rules:
    - host: test.iot.store
      http:
        paths:
          - backend:
              serviceName: turing-web
              servicePort: 80