apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: turing-es
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: turing-es
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: turing-es
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
    metadata:
      labels:
        app.kubernetes.io/name: turing-es
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms2g -Xmx2g
        - name: cluster.name
          valueFrom:
            configMapKeyRef:
              key: cluster.name
              name: es-config
              optional: false
        image: elasticsearch:6.6.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 9300
          timeoutSeconds: 2
        name: turing-es
        ports:
          - containerPort: 9200
            name: 9200tcp02
            protocol: TCP
          - containerPort: 9300
            name: 9300tcp02
            protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 9300
          timeoutSeconds: 2
        resources:
          requests:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-data
      nodeName: worker06
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/es
          type: DirectoryOrCreate
        name: es-data