apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: turing-admin
spec:
  ports:
  - name: 8762tcp02
    port: 8762
    protocol: TCP
    targetPort: 8762
  selector:
    workload.user.cattle.io/workloadselector: deployment-turing-turing-admin
  type: ClusterIP
