apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: turing-datahandler
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: turing-datahandler
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: turing-datahandler
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: turing-datahandler
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - image: hub.iot.store/turing/turing-datahandler:V1.7.0-RELEASE
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 2
            successThreshold: 1
            tcpSocket:
              port: 2345
            timeoutSeconds: 2
          name: turing-datahandler
          ports:
            - containerPort: 2345
              name: 2345tcp02
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 2
            successThreshold: 2
            tcpSocket:
              port: 2345
            timeoutSeconds: 2
          resources:
            requests:
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
      imagePullSecrets:
        - name: hub-iot
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
