apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: turing-web
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: turing-web
spec:
  ports:
  - name: 80tcp02
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: turing-web
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
