apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: turing-rabbitmq
spec:
  ports:
  - name: 15672tcp02
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: 15671tcp02
    port: 15671
    protocol: TCP
    targetPort: 15671
  selector:
    workload.user.cattle.io/workloadselector: deployment-turing-turing-rabbitmq
  type: ClusterIP
