apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: turing-rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: turing-rabbitmq
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: turing-rabbitmq
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: turing-rabbitmq
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: turing2019
        - name: RABBITMQ_DEFAULT_USER
          value: root
        image: rabbitmq:3.6.5-management
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 15672
          timeoutSeconds: 2
        name: turing-rabbitmq
        ports:
        - containerPort: 15672
          name: 15672tcp02
          protocol: TCP
        - containerPort: 15671
          name: 15671tcp02
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 15672
          timeoutSeconds: 2
        resources:
          requests:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      nodeName: worker04
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/rabbitmq
          type: DirectoryOrCreate
        name: rabbitmq-data