apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: turing-mysql
spec:
  ports:
  - name: 3306tcp01-turing-mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    workload.user.cattle.io/workloadselector: deployment-turing-turing-mysql
  type: ClusterIP
