apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: turing-auth
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: turing-auth
spec:
  ports:
    - name: 9777tcp02
      port: 9777
      protocol: TCP
      targetPort: 9777
  selector:
    app.kubernetes.io/name: turing-auth
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
