apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: turing-device
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: turing-device
spec:
  ports:
    - name: 8765tcp02
      port: 8765
      protocol: TCP
      targetPort: 8765
  selector:
    app.kubernetes.io/name: turing-device
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
