apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: turing-admin
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: turing-admin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: turing-admin
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: turing-admin
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - image: hub.iot.store/turing/turing-admin:V1.7.0-RELEASE
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 2
            successThreshold: 1
            tcpSocket:
              port: 8762
            timeoutSeconds: 2
          name: turing-admin
          ports:
            - containerPort: 8762
              name: 8762tcp02
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 2
            successThreshold: 2
            tcpSocket:
              port: 8762
            timeoutSeconds: 2
          resources:
            requests:
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
      imagePullSecrets:
        - name: hub-iot
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
