apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: turing-config
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: turing-config
spec:
  ports:
  - name: 8750tcp02
    port: 8750
    protocol: TCP
    targetPort: 8750
  selector:
    app.kubernetes.io/name: turing-config
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
