apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: turing-auth
spec:
  ports:
  - name: 9777tcp02
    port: 9777
    protocol: TCP
    targetPort: 9777
  selector:
    workload.user.cattle.io/workloadselector: deployment-turing-turing-auth
  type: ClusterIP
