apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: turing-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: turing-redis
spec:
  ports:
    - name: 6379tcp02
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app.kubernetes.io/name: turing-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
status:
  loadBalancer: {}
