apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: turing-datahandler
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: turing-datahandler
spec:
  ports:
  - name: 2345tcp02
    port: 2345
    protocol: TCP
    targetPort: 2345
  selector:
    app.kubernetes.io/name: turing-datahandler
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
